services:
    woodpecker-server:
        image: woodpeckerci/woodpecker-server:v3
        container_name: woodpecker-server
        restart: unless-stopped
        volumes:
            - woodpecker-server-data:/var/lib/woodpecker/
        env_file:
            - path: ./.env
              required: true
        networks:
            - caddy_network

volumes:
    woodpecker-server-data:

networks:
    caddy_network:
        external: true
