services:
    woodpecker-agent:
        image: woodpeckerci/woodpecker-agent:v3
        container_name: woodpecker-agent
        command: agent
        restart: unless-stopped
        volumes:
            - woodpecker-agent-config:/etc/woodpecker
            - /var/run/docker.sock:/var/run/docker.sock
        env_file:
            - path: ./.env


volumes:
    woodpecker-agent-config:
